yiko:
  uploadPath: D:/var/uploaded_files/
  wechatfile: d:/wechatfile/fileupload/
  ymsPath: http://172.16.120.111/
  templatefile: d:\develop\zcwx\
  uploadMateriasTemplate: d:\develop\uploadMateriasTemplate\
  wxServerPath: http://172.16.128.33/zcWechat/

#同步部门接口地址
  pullDepart: http://172.16.120.111/main?xwl=2439KD5MA3WZ&method=getDeparts
#同步事项接口地址
  pullAffairs: http://172.16.120.111/main?xwl=2439KD5MA3WZ&method=getAffairs
#同步办事指南接口地址
  pullAffairGuide: http://172.16.120.111/main?xwl=2439KD5MA3WZ&method=getAffairGuide&affair_id=
#同步事项对象接口地址
  pullAffairObject: http://172.16.120.111/main?xwl=2439KD5MA3WZ&method=getObjsByAffair&affair_id=
#同步事项材料接口地址
  pullAffairMaterials: http://172.16.120.111/main?xwl=2439KD5MA3WZ&method=getMaterialsByAffair
#  wxServerPath: http://192.168.1.213:8099/

logging:
  level:
    root: info
    com.yiko: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
 #   driverClassName: com.mysql.jdbc.Driver
 #   url: jdbc:mysql://127.0.0.1:3306/yiko?useUnicode=true&characterEncoding=utf8
 #   username: root
 #   password: root


    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.1.29:1479;databaseName=QUEUE_ZC
#    url: jdbc:sqlserver://19.134.193.95:1433;databaseName=QUEUE_ZC
    url: jdbc:sqlserver://192.168.127.128:1433;databaseName=QUEUE_ZC
#    url: jdbc:sqlserver://localhost:1479;databaseName=QUEUE_ZC
#    url: jdbc:sqlserver://19.134.193.95:1433;failoverPartner = 19.133.185.92;databaseName=QUEUE_ZC
    username: sa
#    password: abc123@#
    password: frh1487521
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: localhost
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 60000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  cache:
    ehcache:
      config:



